project:
  type: website

website:
  page-footer:
    background: primary
    left: "&copy:2026, Ian Dahlquist"
    center: "Built with [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/iandahlquist

  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - page1.qmd
      - page2.qmd
      - page3.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
