project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - page1.qmd
      - page2.qmd
      - page3.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
