project:
  type: website

website:
  page-footer:
    background: primary
    left: "&copy:2026, Ian Dahlquist"
    center: "Built with [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/iandahlquist

  title: "myminidocs"
  
  sidebar:
    style: "docked"
    background: secondary
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - page1.qmd
      - page2.qmd
      - page3.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: false